services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=pg_db
      - DB_NAME=pos_dbname
      - DB_USER=pos_user
      - DB_PASS=pos_psw
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - pg_db

  pg_db:
    image: postgres:14.6-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pos_user
      - POSTGRES_PASSWORD=pos_psw
      - POSTGRES_DB=pos_dbname
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pg_db
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@enjiru.ru
      - PGADMIN_DEFAULT_PASSWORD=enjiru_code_pos #Если сменить здесь, то нужно удалить контейнер
#      - PGADMIN_LISTEN_ADDRESS=0.0.0.0 #Чтобы не было косяков с nginx лучше в одну сеть с web
#      - PGADMIN_LISTEN_PORT=5555
    ports:
      - "5555:80"

